export const IPC_CHANNELS = {
  READ_DIRECTORY: 'fs:read-directory',
  READ_FILE: 'fs:read-file',
  FILE_CHANGED: 'fs:file-changed',
  FILE_ADDED: 'fs:file-added',
  FILE_REMOVED: 'fs:file-removed',
  GET_CONFIG: 'app:get-config',
  GET_SIDEBAR_WIDTH: 'app:get-sidebar-width',
  SET_SIDEBAR_WIDTH: 'app:set-sidebar-width',
  OPEN_EXTERNAL_LINK: 'shell:open-external-link',
  SELECT_DIRECTORY: 'app:select-directory',
  GET_ZOOM_LEVEL: 'app:get-zoom-level',
  SET_ZOOM_LEVEL: 'app:set-zoom-level',
  TERMINAL_ACTIVATE: 'terminal:activate',
  TERMINAL_GET_INFO: 'terminal:get-info',
  WINDOWS_GET_ALL: 'windows:get-all',
  WINDOWS_ACTIVATE: 'windows:activate',
  WINDOWS_OPEN_NEW: 'windows:open-new',
  SET_CURRENT_FILE: 'app:set-current-file',
} as const;

export const DEFAULTS = {
  WINDOW_WIDTH: 1200,
  WINDOW_HEIGHT: 800,
  MIN_WINDOW_WIDTH: 600,
  MIN_WINDOW_HEIGHT: 400,
  SIDEBAR_WIDTH: 240,
  SIDEBAR_MIN_WIDTH: 180,
  SIDEBAR_MAX_WIDTH: 400,
  ZOOM_STEP: 0.5,
  ZOOM_MIN: -3,
  ZOOM_MAX: 3,
} as const;
